OP_PERMISSIONS = [
    (permissions.ACTION_CAN_READ, permissions.RESOURCE_CONFIG),
    (permissions.ACTION_CAN_ACCESS_MENU, permissions.RESOURCE_ADMIN_MENU),
    (permissions.ACTION_CAN_ACCESS_MENU, permissions.RESOURCE_CONNECTION),
    (permissions.ACTION_CAN_ACCESS_MENU, permissions.RESOURCE_POOL),
    (permissions.ACTION_CAN_ACCESS_MENU, permissions.RESOURCE_VARIABLE),
    (permissions.ACTION_CAN_ACCESS_MENU, permissions.RESOURCE_XCOM),
    (permissions.ACTION_CAN_CREATE, permissions.RESOURCE_CONNECTION),
    (permissions.ACTION_CAN_READ, permissions.RESOURCE_CONNECTION),
    (permissions.ACTION_CAN_EDIT, permissions.RESOURCE_CONNECTION),
    (permissions.ACTION_CAN_DELETE, permissions.RESOURCE_CONNECTION),
    (permissions.ACTION_CAN_CREATE, permissions.RESOURCE_POOL),
    (permissions.ACTION_CAN_READ, permissions.RESOURCE_POOL),
    (permissions.ACTION_CAN_EDIT, permissions.RESOURCE_POOL),
    (permissions.ACTION_CAN_DELETE, permissions.RESOURCE_POOL),
    (permissions.ACTION_CAN_CREATE, permissions.RESOURCE_VARIABLE),
    (permissions.ACTION_CAN_READ, permissions.RESOURCE_VARIABLE),
    (permissions.ACTION_CAN_EDIT, permissions.RESOURCE_VARIABLE),
    (permissions.ACTION_CAN_DELETE, permissions.RESOURCE_VARIABLE),
    (permissions.ACTION_CAN_DELETE, permissions.RESOURCE_XCOM),
]