VIEWER_PERMISSIONS = [
    (permissions.ACTION_CAN_READ, permissions.RESOURCE_AUDIT_LOG),
    (permissions.ACTION_CAN_READ, permissions.RESOURCE_DAG),
    (permissions.ACTION_CAN_READ, permissions.RESOURCE_DAG_DEPENDENCIES),
    (permissions.ACTION_CAN_READ, permissions.RESOURCE_DAG_CODE),
    (permissions.ACTION_CAN_READ, permissions.RESOURCE_DAG_RUN),
    (permissions.ACTION_CAN_READ, permissions.RESOURCE_IMPORT_ERROR),
    (permissions.ACTION_CAN_READ, permissions.RESOURCE_JOB),
    (permissions.ACTION_CAN_READ, permissions.RESOURCE_MY_PASSWORD),
    (permissions.ACTION_CAN_EDIT, permissions.RESOURCE_MY_PASSWORD),
    (permissions.ACTION_CAN_READ, permissions.RESOURCE_MY_PROFILE),
    (permissions.ACTION_CAN_EDIT, permissions.RESOURCE_MY_PROFILE),
    (permissions.ACTION_CAN_READ, permissions.RESOURCE_PLUGIN),
    (permissions.ACTION_CAN_READ, permissions.RESOURCE_SLA_MISS),
    (permissions.ACTION_CAN_READ, permissions.RESOURCE_TASK_INSTANCE),
    (permissions.ACTION_CAN_READ, permissions.RESOURCE_TASK_LOG),
    (permissions.ACTION_CAN_READ, permissions.RESOURCE_XCOM),
    (permissions.ACTION_CAN_READ, permissions.RESOURCE_WEBSITE),
    (permissions.ACTION_CAN_ACCESS_MENU, permissions.RESOURCE_BROWSE_MENU),
    (permissions.ACTION_CAN_ACCESS_MENU, permissions.RESOURCE_DAG_RUN),
    (permissions.ACTION_CAN_ACCESS_MENU, permissions.RESOURCE_DOCS),
    (permissions.ACTION_CAN_ACCESS_MENU, permissions.RESOURCE_DOCS_MENU),
    (permissions.ACTION_CAN_ACCESS_MENU, permissions.RESOURCE_JOB),
    (permissions.ACTION_CAN_ACCESS_MENU, permissions.RESOURCE_AUDIT_LOG),
    (permissions.ACTION_CAN_ACCESS_MENU, permissions.RESOURCE_PLUGIN),
    (permissions.ACTION_CAN_ACCESS_MENU, permissions.RESOURCE_SLA_MISS),
    (permissions.ACTION_CAN_ACCESS_MENU, permissions.RESOURCE_TASK_INSTANCE),
]