// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: eleventh.proto

#include "eleventh.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_eleventh_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_AccountOverview_eleventh_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_eleventh_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_ProfitDetail_eleventh_2eproto;
namespace mam {
class SaveRequestDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<SaveRequest> _instance;
} _SaveRequest_default_instance_;
class AccountOverviewDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<AccountOverview> _instance;
} _AccountOverview_default_instance_;
class ProfitDetailDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<ProfitDetail> _instance;
} _ProfitDetail_default_instance_;
}  // namespace mam
static void InitDefaultsscc_info_AccountOverview_eleventh_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::mam::_AccountOverview_default_instance_;
    new (ptr) ::mam::AccountOverview();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::mam::AccountOverview::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_AccountOverview_eleventh_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_AccountOverview_eleventh_2eproto}, {}};

static void InitDefaultsscc_info_ProfitDetail_eleventh_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::mam::_ProfitDetail_default_instance_;
    new (ptr) ::mam::ProfitDetail();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::mam::ProfitDetail::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_ProfitDetail_eleventh_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_ProfitDetail_eleventh_2eproto}, {}};

static void InitDefaultsscc_info_SaveRequest_eleventh_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::mam::_SaveRequest_default_instance_;
    new (ptr) ::mam::SaveRequest();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::mam::SaveRequest::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<2> scc_info_SaveRequest_eleventh_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 2, 0, InitDefaultsscc_info_SaveRequest_eleventh_2eproto}, {
      &scc_info_AccountOverview_eleventh_2eproto.base,
      &scc_info_ProfitDetail_eleventh_2eproto.base,}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_eleventh_2eproto[3];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_eleventh_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_eleventh_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_eleventh_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::mam::SaveRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::mam::SaveRequest, date_),
  PROTOBUF_FIELD_OFFSET(::mam::SaveRequest, strs_),
  PROTOBUF_FIELD_OFFSET(::mam::SaveRequest, account_overview_),
  PROTOBUF_FIELD_OFFSET(::mam::SaveRequest, profit_detail_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::mam::AccountOverview, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::mam::AccountOverview, accountid_),
  PROTOBUF_FIELD_OFFSET(::mam::AccountOverview, turnover_),
  PROTOBUF_FIELD_OFFSET(::mam::AccountOverview, rate_),
  PROTOBUF_FIELD_OFFSET(::mam::AccountOverview, fee_),
  PROTOBUF_FIELD_OFFSET(::mam::AccountOverview, profit_),
  PROTOBUF_FIELD_OFFSET(::mam::AccountOverview, canceled_),
  PROTOBUF_FIELD_OFFSET(::mam::AccountOverview, failed_),
  PROTOBUF_FIELD_OFFSET(::mam::AccountOverview, acceptcost_),
  PROTOBUF_FIELD_OFFSET(::mam::AccountOverview, matchcost_),
  PROTOBUF_FIELD_OFFSET(::mam::AccountOverview, base_),
  PROTOBUF_FIELD_OFFSET(::mam::AccountOverview, close_profit_),
  PROTOBUF_FIELD_OFFSET(::mam::AccountOverview, server_),
  PROTOBUF_FIELD_OFFSET(::mam::AccountOverview, group_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::mam::ProfitDetail, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::mam::ProfitDetail, accountid_),
  PROTOBUF_FIELD_OFFSET(::mam::ProfitDetail, symbol_),
  PROTOBUF_FIELD_OFFSET(::mam::ProfitDetail, cfgvol_),
  PROTOBUF_FIELD_OFFSET(::mam::ProfitDetail, buyvol_),
  PROTOBUF_FIELD_OFFSET(::mam::ProfitDetail, sellvol_),
  PROTOBUF_FIELD_OFFSET(::mam::ProfitDetail, buyamount_),
  PROTOBUF_FIELD_OFFSET(::mam::ProfitDetail, sellamount_),
  PROTOBUF_FIELD_OFFSET(::mam::ProfitDetail, floatprofit_),
  PROTOBUF_FIELD_OFFSET(::mam::ProfitDetail, settleprofit_),
  PROTOBUF_FIELD_OFFSET(::mam::ProfitDetail, fee_),
  PROTOBUF_FIELD_OFFSET(::mam::ProfitDetail, server_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::mam::SaveRequest)},
  { 9, -1, sizeof(::mam::AccountOverview)},
  { 27, -1, sizeof(::mam::ProfitDetail)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::mam::_SaveRequest_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::mam::_AccountOverview_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::mam::_ProfitDetail_default_instance_),
};

const char descriptor_table_protodef_eleventh_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\016eleventh.proto\022\003mam\"\203\001\n\013SaveRequest\022\014\n"
  "\004date\030\001 \001(\t\022\014\n\004strs\030\002 \003(\t\022.\n\020account_ove"
  "rview\030\003 \003(\0132\024.mam.AccountOverview\022(\n\rpro"
  "fit_detail\030\004 \003(\0132\021.mam.ProfitDetail\"\355\001\n\017"
  "AccountOverview\022\021\n\taccountid\030\001 \001(\005\022\020\n\010tu"
  "rnover\030\002 \001(\001\022\014\n\004rate\030\003 \001(\001\022\013\n\003fee\030\004 \001(\001\022"
  "\016\n\006profit\030\005 \001(\001\022\020\n\010canceled\030\006 \001(\001\022\016\n\006fai"
  "led\030\007 \001(\001\022\022\n\nacceptcost\030\010 \001(\001\022\021\n\tmatchco"
  "st\030\t \001(\001\022\014\n\004base\030\n \001(\001\022\024\n\014close_profit\030\013"
  " \001(\001\022\016\n\006server\030\014 \001(\005\022\r\n\005group\030\r \001(\t\"\321\001\n\014"
  "ProfitDetail\022\021\n\taccountid\030\001 \001(\005\022\016\n\006symbo"
  "l\030\002 \001(\t\022\016\n\006cfgvol\030\003 \001(\005\022\016\n\006buyvol\030\004 \001(\005\022"
  "\017\n\007sellvol\030\005 \001(\005\022\021\n\tbuyamount\030\006 \001(\001\022\022\n\ns"
  "ellamount\030\007 \001(\001\022\023\n\013floatprofit\030\010 \001(\001\022\024\n\014"
  "settleprofit\030\t \001(\001\022\013\n\003fee\030\n \001(\001\022\016\n\006serve"
  "r\030\013 \001(\005b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_eleventh_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_eleventh_2eproto_sccs[3] = {
  &scc_info_AccountOverview_eleventh_2eproto.base,
  &scc_info_ProfitDetail_eleventh_2eproto.base,
  &scc_info_SaveRequest_eleventh_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_eleventh_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_eleventh_2eproto = {
  false, false, descriptor_table_protodef_eleventh_2eproto, "eleventh.proto", 615,
  &descriptor_table_eleventh_2eproto_once, descriptor_table_eleventh_2eproto_sccs, descriptor_table_eleventh_2eproto_deps, 3, 0,
  schemas, file_default_instances, TableStruct_eleventh_2eproto::offsets,
  file_level_metadata_eleventh_2eproto, 3, file_level_enum_descriptors_eleventh_2eproto, file_level_service_descriptors_eleventh_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_eleventh_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_eleventh_2eproto)), true);
namespace mam {

// ===================================================================

void SaveRequest::InitAsDefaultInstance() {
}
class SaveRequest::_Internal {
 public:
};

SaveRequest::SaveRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  strs_(arena),
  account_overview_(arena),
  profit_detail_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:mam.SaveRequest)
}
SaveRequest::SaveRequest(const SaveRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      strs_(from.strs_),
      account_overview_(from.account_overview_),
      profit_detail_(from.profit_detail_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  date_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_date().empty()) {
    date_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_date(),
      GetArena());
  }
  // @@protoc_insertion_point(copy_constructor:mam.SaveRequest)
}

void SaveRequest::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_SaveRequest_eleventh_2eproto.base);
  date_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

SaveRequest::~SaveRequest() {
  // @@protoc_insertion_point(destructor:mam.SaveRequest)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void SaveRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  date_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void SaveRequest::ArenaDtor(void* object) {
  SaveRequest* _this = reinterpret_cast< SaveRequest* >(object);
  (void)_this;
}
void SaveRequest::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void SaveRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const SaveRequest& SaveRequest::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_SaveRequest_eleventh_2eproto.base);
  return *internal_default_instance();
}


void SaveRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:mam.SaveRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  strs_.Clear();
  account_overview_.Clear();
  profit_detail_.Clear();
  date_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SaveRequest::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string date = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_date();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "mam.SaveRequest.date"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated string strs = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_strs();
            ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "mam.SaveRequest.strs"));
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else goto handle_unusual;
        continue;
      // repeated .mam.AccountOverview account_overview = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_account_overview(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<26>(ptr));
        } else goto handle_unusual;
        continue;
      // repeated .mam.ProfitDetail profit_detail = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_profit_detail(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<34>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* SaveRequest::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:mam.SaveRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string date = 1;
  if (this->date().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_date().data(), static_cast<int>(this->_internal_date().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "mam.SaveRequest.date");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_date(), target);
  }

  // repeated string strs = 2;
  for (int i = 0, n = this->_internal_strs_size(); i < n; i++) {
    const auto& s = this->_internal_strs(i);
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      s.data(), static_cast<int>(s.length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "mam.SaveRequest.strs");
    target = stream->WriteString(2, s, target);
  }

  // repeated .mam.AccountOverview account_overview = 3;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_account_overview_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, this->_internal_account_overview(i), target, stream);
  }

  // repeated .mam.ProfitDetail profit_detail = 4;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_profit_detail_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(4, this->_internal_profit_detail(i), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mam.SaveRequest)
  return target;
}

size_t SaveRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:mam.SaveRequest)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated string strs = 2;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(strs_.size());
  for (int i = 0, n = strs_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
      strs_.Get(i));
  }

  // repeated .mam.AccountOverview account_overview = 3;
  total_size += 1UL * this->_internal_account_overview_size();
  for (const auto& msg : this->account_overview_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated .mam.ProfitDetail profit_detail = 4;
  total_size += 1UL * this->_internal_profit_detail_size();
  for (const auto& msg : this->profit_detail_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // string date = 1;
  if (this->date().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_date());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SaveRequest::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:mam.SaveRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const SaveRequest* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<SaveRequest>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:mam.SaveRequest)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:mam.SaveRequest)
    MergeFrom(*source);
  }
}

void SaveRequest::MergeFrom(const SaveRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:mam.SaveRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  strs_.MergeFrom(from.strs_);
  account_overview_.MergeFrom(from.account_overview_);
  profit_detail_.MergeFrom(from.profit_detail_);
  if (from.date().size() > 0) {
    _internal_set_date(from._internal_date());
  }
}

void SaveRequest::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:mam.SaveRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SaveRequest::CopyFrom(const SaveRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mam.SaveRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SaveRequest::IsInitialized() const {
  return true;
}

void SaveRequest::InternalSwap(SaveRequest* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  strs_.InternalSwap(&other->strs_);
  account_overview_.InternalSwap(&other->account_overview_);
  profit_detail_.InternalSwap(&other->profit_detail_);
  date_.Swap(&other->date_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}

::PROTOBUF_NAMESPACE_ID::Metadata SaveRequest::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void AccountOverview::InitAsDefaultInstance() {
}
class AccountOverview::_Internal {
 public:
};

AccountOverview::AccountOverview(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:mam.AccountOverview)
}
AccountOverview::AccountOverview(const AccountOverview& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  group_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_group().empty()) {
    group_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_group(),
      GetArena());
  }
  ::memcpy(&turnover_, &from.turnover_,
    static_cast<size_t>(reinterpret_cast<char*>(&close_profit_) -
    reinterpret_cast<char*>(&turnover_)) + sizeof(close_profit_));
  // @@protoc_insertion_point(copy_constructor:mam.AccountOverview)
}

void AccountOverview::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_AccountOverview_eleventh_2eproto.base);
  group_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&turnover_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&close_profit_) -
      reinterpret_cast<char*>(&turnover_)) + sizeof(close_profit_));
}

AccountOverview::~AccountOverview() {
  // @@protoc_insertion_point(destructor:mam.AccountOverview)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void AccountOverview::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  group_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void AccountOverview::ArenaDtor(void* object) {
  AccountOverview* _this = reinterpret_cast< AccountOverview* >(object);
  (void)_this;
}
void AccountOverview::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void AccountOverview::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const AccountOverview& AccountOverview::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_AccountOverview_eleventh_2eproto.base);
  return *internal_default_instance();
}


void AccountOverview::Clear() {
// @@protoc_insertion_point(message_clear_start:mam.AccountOverview)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  group_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::memset(&turnover_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&close_profit_) -
      reinterpret_cast<char*>(&turnover_)) + sizeof(close_profit_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* AccountOverview::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // int32 accountid = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          accountid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // double turnover = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 17)) {
          turnover_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // double rate = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 25)) {
          rate_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // double fee = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 33)) {
          fee_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // double profit = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 41)) {
          profit_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // double canceled = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 49)) {
          canceled_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // double failed = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 57)) {
          failed_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // double acceptcost = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 65)) {
          acceptcost_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // double matchcost = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 73)) {
          matchcost_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // double base = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 81)) {
          base_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // double close_profit = 11;
      case 11:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 89)) {
          close_profit_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // int32 server = 12;
      case 12:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 96)) {
          server_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string group = 13;
      case 13:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 106)) {
          auto str = _internal_mutable_group();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "mam.AccountOverview.group"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* AccountOverview::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:mam.AccountOverview)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 accountid = 1;
  if (this->accountid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->_internal_accountid(), target);
  }

  // double turnover = 2;
  if (!(this->turnover() <= 0 && this->turnover() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(2, this->_internal_turnover(), target);
  }

  // double rate = 3;
  if (!(this->rate() <= 0 && this->rate() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(3, this->_internal_rate(), target);
  }

  // double fee = 4;
  if (!(this->fee() <= 0 && this->fee() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(4, this->_internal_fee(), target);
  }

  // double profit = 5;
  if (!(this->profit() <= 0 && this->profit() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(5, this->_internal_profit(), target);
  }

  // double canceled = 6;
  if (!(this->canceled() <= 0 && this->canceled() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(6, this->_internal_canceled(), target);
  }

  // double failed = 7;
  if (!(this->failed() <= 0 && this->failed() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(7, this->_internal_failed(), target);
  }

  // double acceptcost = 8;
  if (!(this->acceptcost() <= 0 && this->acceptcost() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(8, this->_internal_acceptcost(), target);
  }

  // double matchcost = 9;
  if (!(this->matchcost() <= 0 && this->matchcost() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(9, this->_internal_matchcost(), target);
  }

  // double base = 10;
  if (!(this->base() <= 0 && this->base() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(10, this->_internal_base(), target);
  }

  // double close_profit = 11;
  if (!(this->close_profit() <= 0 && this->close_profit() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(11, this->_internal_close_profit(), target);
  }

  // int32 server = 12;
  if (this->server() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(12, this->_internal_server(), target);
  }

  // string group = 13;
  if (this->group().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_group().data(), static_cast<int>(this->_internal_group().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "mam.AccountOverview.group");
    target = stream->WriteStringMaybeAliased(
        13, this->_internal_group(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mam.AccountOverview)
  return target;
}

size_t AccountOverview::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:mam.AccountOverview)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string group = 13;
  if (this->group().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_group());
  }

  // double turnover = 2;
  if (!(this->turnover() <= 0 && this->turnover() >= 0)) {
    total_size += 1 + 8;
  }

  // double rate = 3;
  if (!(this->rate() <= 0 && this->rate() >= 0)) {
    total_size += 1 + 8;
  }

  // double fee = 4;
  if (!(this->fee() <= 0 && this->fee() >= 0)) {
    total_size += 1 + 8;
  }

  // double profit = 5;
  if (!(this->profit() <= 0 && this->profit() >= 0)) {
    total_size += 1 + 8;
  }

  // double canceled = 6;
  if (!(this->canceled() <= 0 && this->canceled() >= 0)) {
    total_size += 1 + 8;
  }

  // int32 accountid = 1;
  if (this->accountid() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_accountid());
  }

  // int32 server = 12;
  if (this->server() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_server());
  }

  // double failed = 7;
  if (!(this->failed() <= 0 && this->failed() >= 0)) {
    total_size += 1 + 8;
  }

  // double acceptcost = 8;
  if (!(this->acceptcost() <= 0 && this->acceptcost() >= 0)) {
    total_size += 1 + 8;
  }

  // double matchcost = 9;
  if (!(this->matchcost() <= 0 && this->matchcost() >= 0)) {
    total_size += 1 + 8;
  }

  // double base = 10;
  if (!(this->base() <= 0 && this->base() >= 0)) {
    total_size += 1 + 8;
  }

  // double close_profit = 11;
  if (!(this->close_profit() <= 0 && this->close_profit() >= 0)) {
    total_size += 1 + 8;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void AccountOverview::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:mam.AccountOverview)
  GOOGLE_DCHECK_NE(&from, this);
  const AccountOverview* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<AccountOverview>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:mam.AccountOverview)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:mam.AccountOverview)
    MergeFrom(*source);
  }
}

void AccountOverview::MergeFrom(const AccountOverview& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:mam.AccountOverview)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.group().size() > 0) {
    _internal_set_group(from._internal_group());
  }
  if (!(from.turnover() <= 0 && from.turnover() >= 0)) {
    _internal_set_turnover(from._internal_turnover());
  }
  if (!(from.rate() <= 0 && from.rate() >= 0)) {
    _internal_set_rate(from._internal_rate());
  }
  if (!(from.fee() <= 0 && from.fee() >= 0)) {
    _internal_set_fee(from._internal_fee());
  }
  if (!(from.profit() <= 0 && from.profit() >= 0)) {
    _internal_set_profit(from._internal_profit());
  }
  if (!(from.canceled() <= 0 && from.canceled() >= 0)) {
    _internal_set_canceled(from._internal_canceled());
  }
  if (from.accountid() != 0) {
    _internal_set_accountid(from._internal_accountid());
  }
  if (from.server() != 0) {
    _internal_set_server(from._internal_server());
  }
  if (!(from.failed() <= 0 && from.failed() >= 0)) {
    _internal_set_failed(from._internal_failed());
  }
  if (!(from.acceptcost() <= 0 && from.acceptcost() >= 0)) {
    _internal_set_acceptcost(from._internal_acceptcost());
  }
  if (!(from.matchcost() <= 0 && from.matchcost() >= 0)) {
    _internal_set_matchcost(from._internal_matchcost());
  }
  if (!(from.base() <= 0 && from.base() >= 0)) {
    _internal_set_base(from._internal_base());
  }
  if (!(from.close_profit() <= 0 && from.close_profit() >= 0)) {
    _internal_set_close_profit(from._internal_close_profit());
  }
}

void AccountOverview::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:mam.AccountOverview)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void AccountOverview::CopyFrom(const AccountOverview& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mam.AccountOverview)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AccountOverview::IsInitialized() const {
  return true;
}

void AccountOverview::InternalSwap(AccountOverview* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  group_.Swap(&other->group_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(AccountOverview, close_profit_)
      + sizeof(AccountOverview::close_profit_)
      - PROTOBUF_FIELD_OFFSET(AccountOverview, turnover_)>(
          reinterpret_cast<char*>(&turnover_),
          reinterpret_cast<char*>(&other->turnover_));
}

::PROTOBUF_NAMESPACE_ID::Metadata AccountOverview::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void ProfitDetail::InitAsDefaultInstance() {
}
class ProfitDetail::_Internal {
 public:
};

ProfitDetail::ProfitDetail(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:mam.ProfitDetail)
}
ProfitDetail::ProfitDetail(const ProfitDetail& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  symbol_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_symbol().empty()) {
    symbol_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_symbol(),
      GetArena());
  }
  ::memcpy(&accountid_, &from.accountid_,
    static_cast<size_t>(reinterpret_cast<char*>(&server_) -
    reinterpret_cast<char*>(&accountid_)) + sizeof(server_));
  // @@protoc_insertion_point(copy_constructor:mam.ProfitDetail)
}

void ProfitDetail::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_ProfitDetail_eleventh_2eproto.base);
  symbol_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&accountid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&server_) -
      reinterpret_cast<char*>(&accountid_)) + sizeof(server_));
}

ProfitDetail::~ProfitDetail() {
  // @@protoc_insertion_point(destructor:mam.ProfitDetail)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void ProfitDetail::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  symbol_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void ProfitDetail::ArenaDtor(void* object) {
  ProfitDetail* _this = reinterpret_cast< ProfitDetail* >(object);
  (void)_this;
}
void ProfitDetail::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void ProfitDetail::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ProfitDetail& ProfitDetail::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_ProfitDetail_eleventh_2eproto.base);
  return *internal_default_instance();
}


void ProfitDetail::Clear() {
// @@protoc_insertion_point(message_clear_start:mam.ProfitDetail)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  symbol_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::memset(&accountid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&server_) -
      reinterpret_cast<char*>(&accountid_)) + sizeof(server_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ProfitDetail::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // int32 accountid = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          accountid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string symbol = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_symbol();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "mam.ProfitDetail.symbol"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 cfgvol = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          cfgvol_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 buyvol = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 32)) {
          buyvol_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 sellvol = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 40)) {
          sellvol_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // double buyamount = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 49)) {
          buyamount_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // double sellamount = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 57)) {
          sellamount_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // double floatprofit = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 65)) {
          floatprofit_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // double settleprofit = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 73)) {
          settleprofit_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // double fee = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 81)) {
          fee_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // int32 server = 11;
      case 11:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 88)) {
          server_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* ProfitDetail::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:mam.ProfitDetail)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 accountid = 1;
  if (this->accountid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->_internal_accountid(), target);
  }

  // string symbol = 2;
  if (this->symbol().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_symbol().data(), static_cast<int>(this->_internal_symbol().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "mam.ProfitDetail.symbol");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_symbol(), target);
  }

  // int32 cfgvol = 3;
  if (this->cfgvol() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(3, this->_internal_cfgvol(), target);
  }

  // int32 buyvol = 4;
  if (this->buyvol() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(4, this->_internal_buyvol(), target);
  }

  // int32 sellvol = 5;
  if (this->sellvol() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(5, this->_internal_sellvol(), target);
  }

  // double buyamount = 6;
  if (!(this->buyamount() <= 0 && this->buyamount() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(6, this->_internal_buyamount(), target);
  }

  // double sellamount = 7;
  if (!(this->sellamount() <= 0 && this->sellamount() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(7, this->_internal_sellamount(), target);
  }

  // double floatprofit = 8;
  if (!(this->floatprofit() <= 0 && this->floatprofit() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(8, this->_internal_floatprofit(), target);
  }

  // double settleprofit = 9;
  if (!(this->settleprofit() <= 0 && this->settleprofit() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(9, this->_internal_settleprofit(), target);
  }

  // double fee = 10;
  if (!(this->fee() <= 0 && this->fee() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(10, this->_internal_fee(), target);
  }

  // int32 server = 11;
  if (this->server() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(11, this->_internal_server(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mam.ProfitDetail)
  return target;
}

size_t ProfitDetail::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:mam.ProfitDetail)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string symbol = 2;
  if (this->symbol().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_symbol());
  }

  // int32 accountid = 1;
  if (this->accountid() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_accountid());
  }

  // int32 cfgvol = 3;
  if (this->cfgvol() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_cfgvol());
  }

  // int32 buyvol = 4;
  if (this->buyvol() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_buyvol());
  }

  // int32 sellvol = 5;
  if (this->sellvol() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_sellvol());
  }

  // double buyamount = 6;
  if (!(this->buyamount() <= 0 && this->buyamount() >= 0)) {
    total_size += 1 + 8;
  }

  // double sellamount = 7;
  if (!(this->sellamount() <= 0 && this->sellamount() >= 0)) {
    total_size += 1 + 8;
  }

  // double floatprofit = 8;
  if (!(this->floatprofit() <= 0 && this->floatprofit() >= 0)) {
    total_size += 1 + 8;
  }

  // double settleprofit = 9;
  if (!(this->settleprofit() <= 0 && this->settleprofit() >= 0)) {
    total_size += 1 + 8;
  }

  // double fee = 10;
  if (!(this->fee() <= 0 && this->fee() >= 0)) {
    total_size += 1 + 8;
  }

  // int32 server = 11;
  if (this->server() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_server());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ProfitDetail::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:mam.ProfitDetail)
  GOOGLE_DCHECK_NE(&from, this);
  const ProfitDetail* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<ProfitDetail>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:mam.ProfitDetail)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:mam.ProfitDetail)
    MergeFrom(*source);
  }
}

void ProfitDetail::MergeFrom(const ProfitDetail& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:mam.ProfitDetail)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.symbol().size() > 0) {
    _internal_set_symbol(from._internal_symbol());
  }
  if (from.accountid() != 0) {
    _internal_set_accountid(from._internal_accountid());
  }
  if (from.cfgvol() != 0) {
    _internal_set_cfgvol(from._internal_cfgvol());
  }
  if (from.buyvol() != 0) {
    _internal_set_buyvol(from._internal_buyvol());
  }
  if (from.sellvol() != 0) {
    _internal_set_sellvol(from._internal_sellvol());
  }
  if (!(from.buyamount() <= 0 && from.buyamount() >= 0)) {
    _internal_set_buyamount(from._internal_buyamount());
  }
  if (!(from.sellamount() <= 0 && from.sellamount() >= 0)) {
    _internal_set_sellamount(from._internal_sellamount());
  }
  if (!(from.floatprofit() <= 0 && from.floatprofit() >= 0)) {
    _internal_set_floatprofit(from._internal_floatprofit());
  }
  if (!(from.settleprofit() <= 0 && from.settleprofit() >= 0)) {
    _internal_set_settleprofit(from._internal_settleprofit());
  }
  if (!(from.fee() <= 0 && from.fee() >= 0)) {
    _internal_set_fee(from._internal_fee());
  }
  if (from.server() != 0) {
    _internal_set_server(from._internal_server());
  }
}

void ProfitDetail::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:mam.ProfitDetail)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ProfitDetail::CopyFrom(const ProfitDetail& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mam.ProfitDetail)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ProfitDetail::IsInitialized() const {
  return true;
}

void ProfitDetail::InternalSwap(ProfitDetail* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  symbol_.Swap(&other->symbol_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ProfitDetail, server_)
      + sizeof(ProfitDetail::server_)
      - PROTOBUF_FIELD_OFFSET(ProfitDetail, accountid_)>(
          reinterpret_cast<char*>(&accountid_),
          reinterpret_cast<char*>(&other->accountid_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ProfitDetail::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace mam
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::mam::SaveRequest* Arena::CreateMaybeMessage< ::mam::SaveRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::mam::SaveRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::mam::AccountOverview* Arena::CreateMaybeMessage< ::mam::AccountOverview >(Arena* arena) {
  return Arena::CreateMessageInternal< ::mam::AccountOverview >(arena);
}
template<> PROTOBUF_NOINLINE ::mam::ProfitDetail* Arena::CreateMaybeMessage< ::mam::ProfitDetail >(Arena* arena) {
  return Arena::CreateMessageInternal< ::mam::ProfitDetail >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
